language: node_js
node_js:
  - '10'
dist: trusty
sudo: false

branches:
  only:
  - master

cache:
  directories:
    - node_modules

install:
  - npm install
script:
  - npx typedoc --out out src/index.ts
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: out/
  on:
    branch: master
